FROM openjdk:21-jdk

WORKDIR /app


COPY spring-cloud-config-server/target/spring-cloud-config-server-0.0.1-SNAPSHOT.jar /app/spring-cloud-config-server-0.0.1-SNAPSHOT.jar
COPY spring-cloud-config-server/src/main/resources/application.properties /app/application.properties
COPY spring-cloud-config-server/src/main/resources/limits-service.properties /app/limits-service.properties
COPY spring-cloud-config-server/src/main/resources/limits-service-dev.properties /app/limits-service-dev.properties
COPY spring-cloud-config-server/src/main/resources/limits-service-qa.properties /app/limits-service-qa.properties


EXPOSE 8888

ENTRYPOINT ["java", "-jar", "/app/spring-cloud-config-server-0.0.1-SNAPSHOT.jar", "--spring.config.additional-location=/app/"]