FROM openjdk:21-jdk

VOLUME /tmp

COPY currency-conversion-service/target/currency-conversion-service-0.0.1-SNAPSHOT.jar /app/currency-conversion-service-0.0.1-SNAPSHOT.jar
COPY currency-conversion-service/src/main/resources/application.properties /app/application.properties

EXPOSE 8100

ENTRYPOINT ["java", "-jar", "/app/currency-conversion-service-0.0.1-SNAPSHOT.jar"]