FROM openjdk:21-jdk

COPY currency-exchange-service/target/currency-exchange-service-0.0.1-SNAPSHOT.jar /app/currency-exchange-service-0.0.1-SNAPSHOT.jar
COPY currency-exchange-service/src/main/resources/application.properties /app/application.properties

EXPOSE 8000

ENTRYPOINT ["java", "-jar", "/app/currency-exchange-service-0.0.1-SNAPSHOT.jar"]