FROM openjdk:21-jdk

workdir /app

COPY limits-service/target/limits-service-0.0.1-SNAPSHOT.jar /app/limits-service-0.0.1-SNAPSHOT.jar
COPY limits-service/src/main/resources/application.properties /app/application.properties

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/limits-service-0.0.1-SNAPSHOT.jar", "--spring.config.additional-location=/app/"]