FROM openjdk:21-jdk

COPY api-gateway/target/api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway-0.0.1-SNAPSHOT.jar
COPY api-gateway/src/main/resources/application.properties /app/application.properties
COPY api-gateway/src/main/resources/application.yml /app/application.yml

EXPOSE 8765

ENTRYPOINT ["java", "-jar", "/app/api-gateway-0.0.1-SNAPSHOT.jar"]